// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH0NWSnL0uufMJCFqtTbGgezTdItJEtyw',
    appId: '1:502231771588:web:cef36baa8dc48a832c1c91',
    messagingSenderId: '502231771588',
    projectId: 'management-assets-cbf92',
    authDomain: 'management-assets-cbf92.firebaseapp.com',
    storageBucket: 'management-assets-cbf92.firebasestorage.app',
    measurementId: 'G-94Z8MVX44D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2yYpNZk0jiN_p65FhiHcdQxaQclFm0jI',
    appId: '1:502231771588:android:c9c82da53466cd182c1c91',
    messagingSenderId: '502231771588',
    projectId: 'management-assets-cbf92',
    storageBucket: 'management-assets-cbf92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeGSGof1tID2e88M-2krACIJ19JOZwq2A',
    appId: '1:502231771588:ios:bbf4d8fbd000634c2c1c91',
    messagingSenderId: '502231771588',
    projectId: 'management-assets-cbf92',
    storageBucket: 'management-assets-cbf92.firebasestorage.app',
    iosBundleId: 'com.example.managementAsset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeGSGof1tID2e88M-2krACIJ19JOZwq2A',
    appId: '1:502231771588:ios:bbf4d8fbd000634c2c1c91',
    messagingSenderId: '502231771588',
    projectId: 'management-assets-cbf92',
    storageBucket: 'management-assets-cbf92.firebasestorage.app',
    iosBundleId: 'com.example.managementAsset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH0NWSnL0uufMJCFqtTbGgezTdItJEtyw',
    appId: '1:502231771588:web:e5f6aa908aa332612c1c91',
    messagingSenderId: '502231771588',
    projectId: 'management-assets-cbf92',
    authDomain: 'management-assets-cbf92.firebaseapp.com',
    storageBucket: 'management-assets-cbf92.firebasestorage.app',
    measurementId: 'G-5EMGY57406',
  );
}
